import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";


export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{                       // Readonly type - can't modify 
	children: React.ReactNode;        // Only should except ReactNode
}>) {                               // children -> content from page.tsx
	return (
		<html lang="en" className="dark">
			<body
				className={`antialiased`}
			>
				<div>
					<Navbar />
				</div>

				{children}
			</body>
		</html>
	);
}
